# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install texlive-fonts-recommended lmodern texlive-xetex texlive-fonts-extra pandoc

      - name: Installing Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb
          sudo dpkg -i pandoc-2.9.1.1-1-amd64.deb
          
      - name: Preparing directories
        run: |
          cd $GITHUB_WORKSPACE
          sudo ln -s $GITHUB_WORKSPACE/img /img
          
      - name: Building PDF
        run: sudo ./make_pdf.sh
        
      - name: Upload PDF
        env:
          WEB_PWD: ${{ secrets.WEB_PWD }}
        run: |
          curl -v https://speeduino.com:2078 || true
          curl -v --tlsv1.2 --ipv4 --user "speeduino_manual@speeduino.com:$WEB_PWD" --basic -T "./offline/Speeduino_manual.pdf" "https://speeduino.com:2078/Speeduino_manual.pdf"
